language: java
jdk:
- oraclejdk8
deploy:
# Bintray release
- provider: script
  script: ./gradlew -PdryRun=false -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_API_KEY bintrayUpload
  skip_cleanup: true
  on:
    repo: rundeck/rundeck-oracle-dialect
    tags: true
# Snapshots
- provider: script
  script: ./gradlew -PsonatypeUsername=$SONATYPE_USER -PsonatypePassword=$SONATYPE_PASSWORD ./gradlew uploadArchives
  skip_cleanup: true
  on:
    repo: rundeck/rundeck-oracle-dialect
    branch: travis-build
    tags: false