language: java
jdk:
- oraclejdk8
deploy:
# Bintray release
- provider: script
  script: bash scripts/publish-release.sh
  skip_cleanup: true
  on:
    repo: rundeck/rundeck-oracle-dialect
    tags: true
# Snapshots
- provider: script
  script: bash scripts/publish-snapshot.sh
  skip_cleanup: true
  on:
    repo: rundeck/rundeck-oracle-dialect
    branch: master
    tags: false