[versions]
axionRelease = "1.18.17"
groovy = "3.0.23"
nexusPublish = "2.0.0"

[plugins]
axionRelease = { id = "pl.allegro.tech.build.axion-release", version.ref = "axionRelease" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }